#####################################
# Settings
#####################################

datasource:
  # driverClassName: org.h2.Driver
  # url: jdbc:h2:mem:sample;MODE=PostgreSQL
  # driverClassName: com.mysql.jdbc.Driver
  # url: "jdbc:mysql://localhost:3306/sample"
  driverClassName: org.postgresql.Driver
  url: "jdbc:postgresql://localhost:5432/sample"
  schema:
  username: postgres
  password: postgres

outputDirectory: "./example/src/main/java/org/example/generated"
basePackage: "org.example.generated"
dataSetPrefix: "Sample"
